import type { ByteCard } from './bytes';

/*
 * The starter pack — correct, sourced, hand-written. Loaded on demand from the
 * Bytes deck ("Load starter pack"). Fixed ids so re-loading dedups instead of
 * duplicating. Cards are stamped with `updatedAt` at load time.
 */
export const STARTER_BYTES: Omit<ByteCard, 'updatedAt'>[] = [
  { id: 'b_ml_attention', pack: 'foundations', topic: 'ml', level: 1, title: 'Attention is a weighted average', blurb: "Each token's new vector is a softmax-weighted sum of every other token's value. The weights ARE the attention — that's how a transformer reads a sentence whole, with no recurrence.", source: 'Vaswani et al., 2017' },
  { id: 'b_ml_gradient', pack: 'foundations', topic: 'ml', level: 1, title: 'Gradient descent walks downhill', blurb: 'The gradient points toward steepest increase of the loss. Step the opposite way, a little at a time, and you slide toward a minimum. The step size is the learning rate.' },
  { id: 'b_ml_lr', pack: 'foundations', topic: 'ml', level: 1, title: 'Learning rate: the Goldilocks knob', blurb: 'Too high and training diverges; too low and it crawls or gets stuck. Most tuning pain is really learning-rate pain.' },
  { id: 'b_ml_overfit', pack: 'foundations', topic: 'ml', level: 2, title: 'Overfitting is memorising', blurb: 'Low training error but high test error means the model memorised noise. Cures: more data, regularisation, dropout, or a simpler model.' },
  { id: 'b_ml_biasvar', pack: 'foundations', topic: 'ml', level: 2, title: 'Bias vs variance', blurb: 'High bias underfits (too simple). High variance overfits (too flexible, swings with the data). You trade one for the other.' },
  { id: 'b_ml_softmax', pack: 'foundations', topic: 'ml', level: 2, title: 'Softmax turns scores into probabilities', blurb: 'Exponentiate each logit, then divide by the sum. Output is positive and sums to 1 — a probability distribution over classes.', code: 'p_i = exp(z_i) / sum(exp(z_j))', lang: 'text' },
  { id: 'b_ml_backprop', pack: 'foundations', topic: 'ml', level: 3, title: 'Backprop is just the chain rule', blurb: "Multiply local derivatives backward through the network to get each weight's effect on the loss. Nothing mystical — calculus, layer by layer." },
  { id: 'b_ai_tokens', pack: 'foundations', topic: 'ai', level: 1, title: 'LLMs think in tokens, not words', blurb: "Text is split into tokens (~4 chars). The model predicts the next token, over and over. The 'context window' is how many it can see at once." },
  { id: 'b_ai_temp', pack: 'foundations', topic: 'ai', level: 2, title: 'Temperature = how bold the guess', blurb: 'It reshapes the next-token odds. Near 0 = always the likeliest token (focused). Higher = flatter odds (creative, riskier).' },
  { id: 'b_ai_halluc', pack: 'foundations', topic: 'ai', level: 2, title: "Why models 'hallucinate'", blurb: 'An LLM predicts plausible text, not verified truth. Fluent-and-wrong is a normal output. Grounding it in real sources (RAG) is how you fight it.' },
  { id: 'b_sql_leftjoin', pack: 'foundations', topic: 'sql', level: 1, title: 'LEFT JOIN keeps every left row', blurb: "Unmatched right-side columns come back NULL — so a LEFT JOIN never drops a row from the left table. Filter for the NULLs to find 'has none'.", code: 'SELECT u.name\nFROM users u\nLEFT JOIN orders o ON o.user_id = u.id\nWHERE o.id IS NULL;', lang: 'sql' },
  { id: 'b_sql_wherehaving', pack: 'foundations', topic: 'sql', level: 2, title: 'WHERE before, HAVING after', blurb: "WHERE filters rows before grouping. HAVING filters groups after aggregation. You can't put an aggregate in WHERE.", code: 'SELECT dept, COUNT(*)\nFROM emp\nGROUP BY dept\nHAVING COUNT(*) > 5;', lang: 'sql' },
  { id: 'b_sql_null', pack: 'foundations', topic: 'sql', level: 1, title: 'NULL equals nothing', blurb: "NULL means 'unknown', so NULL = NULL is not true — it's NULL. Always test with IS NULL / IS NOT NULL, never = NULL." },
  { id: 'b_sql_index', pack: 'foundations', topic: 'sql', level: 2, title: 'Indexes trade writes for reads', blurb: 'An index is a sorted lookup: it makes matching queries fast, but every insert/update must maintain it. Index what you filter and join on — not everything.' },
  { id: 'b_py_comprehension', pack: 'foundations', topic: 'python', level: 1, title: 'Comprehensions build; loops mutate', blurb: 'One expression returns a new list — clearer and faster than appending in a loop.', code: 'squares = [n*n for n in xs if n % 2 == 0]', lang: 'python' },
  { id: 'b_py_defaultarg', pack: 'foundations', topic: 'python', level: 3, title: 'The mutable-default trap', blurb: "A default list is created once, at definition — so it's SHARED across calls and quietly accumulates. Use None and make a fresh one inside.", code: 'def add(x, acc=None):\n    acc = acc or []\n    acc.append(x)\n    return acc', lang: 'python' },
  { id: 'b_py_iseq', pack: 'foundations', topic: 'python', level: 2, title: 'is vs ==', blurb: "== asks 'equal value?'. is asks 'the exact same object?'. Use == for values; reserve is for None." },
  { id: 'b_py_generator', pack: 'foundations', topic: 'python', level: 3, title: 'Generators are lazy', blurb: 'yield produces values one at a time, on demand — so you can stream millions of items without holding them all in memory.', code: 'def evens():\n    n = 0\n    while True:\n        yield n\n        n += 2', lang: 'python' },
  { id: 'b_stat_corr', pack: 'foundations', topic: 'stats', level: 1, title: "Correlation isn't causation", blurb: 'Two things moving together may share a hidden cause, or be coincidence. A correlation is a hypothesis, not a conclusion.' },
  { id: 'b_stat_pvalue', pack: 'foundations', topic: 'stats', level: 3, title: 'What a p-value actually says', blurb: "It's the chance of data this extreme IF the null hypothesis were true. It is NOT the probability the null is true, and not the size of an effect." },
  { id: 'b_stat_median', pack: 'foundations', topic: 'stats', level: 1, title: 'Median shrugs off outliers', blurb: 'One billionaire wrecks the mean income of a room but barely moves the median. For skewed data, the median is the honest "typical".' },
  { id: 'b_cs_bigo', pack: 'foundations', topic: 'cs', level: 1, title: 'Big-O is about growth', blurb: 'It describes how work scales as input grows, ignoring constants. O(n) doubles when input doubles; O(n²) quadruples; O(log n) barely moves.' },
  { id: 'b_cs_hash', pack: 'foundations', topic: 'cs', level: 2, title: 'Hash tables are O(1) on average', blurb: 'A hash maps a key straight to a bucket, so lookup/insert average constant time — the magic behind dict and set. Worst case degrades with collisions.' },
  { id: 'b_cs_idempotent', pack: 'foundations', topic: 'cs', level: 2, title: 'Idempotent = safe to retry', blurb: 'An operation you can run twice with the same result (like PUT or DELETE). It is what lets a flaky network retry without doubling the effect.' },
];

/*
 * The SQL pack — original cards covering the standard Basic-SQL curriculum
 * (SELECT · WHERE · AND/OR/NOT · BETWEEN · IN · LIKE · ORDER BY · grouping).
 * Written from scratch, not lifted from any tutorial; SQL facts, my own words.
 */
export const SQL_BYTES: Omit<ByteCard, 'updatedAt'>[] = [
  { id: 'b_sql_what', pack: 'sql', topic: 'sql', level: 1, title: 'SQL asks questions of tables', blurb: 'SQL reads and writes relational databases — data as rows and columns. You describe WHAT you want back; the engine works out how to fetch it.' },
  { id: 'b_sql_select', pack: 'sql', topic: 'sql', level: 1, title: 'SELECT picks columns', blurb: 'Name the columns you want (or * for all of them) and the table to read from.', code: 'SELECT name, salary\nFROM employees;', lang: 'sql' },
  { id: 'b_sql_where', pack: 'sql', topic: 'sql', level: 1, title: 'WHERE filters rows', blurb: 'It keeps only rows whose condition is true. Text values go in single quotes.', code: "SELECT *\nFROM employees\nWHERE dept = 'Sales';", lang: 'sql' },
  { id: 'b_sql_andornot', pack: 'sql', topic: 'sql', level: 1, title: 'AND, OR, NOT combine conditions', blurb: 'AND needs both true, OR needs either, NOT flips one. Parenthesise to make precedence explicit.', code: "WHERE dept = 'Sales'\n  AND (salary > 50000 OR bonus > 0);", lang: 'sql' },
  { id: 'b_sql_between', pack: 'sql', topic: 'sql', level: 1, title: 'BETWEEN is an inclusive range', blurb: 'BETWEEN a AND b matches from a to b, both endpoints included. Works on numbers, dates and text.', code: 'WHERE age BETWEEN 18 AND 30;', lang: 'sql' },
  { id: 'b_sql_in', pack: 'sql', topic: 'sql', level: 1, title: 'IN matches a set', blurb: 'IN (…) is shorthand for a stack of OR-equals — cleaner than chaining them.', code: "WHERE country IN ('US', 'UK', 'CA');", lang: 'sql' },
  { id: 'b_sql_like', pack: 'sql', topic: 'sql', level: 2, title: 'LIKE matches patterns', blurb: "% stands for any run of characters, _ for exactly one. So 'A%' means starts-with-A.", code: "WHERE name LIKE 'A%'    -- starts with A\n   OR name LIKE '_o%';  -- 'o' as 2nd letter", lang: 'sql' },
  { id: 'b_sql_orderby', pack: 'sql', topic: 'sql', level: 1, title: 'ORDER BY sorts the result', blurb: 'ASC is ascending (the default), DESC descending. List several columns to sort left to right.', code: 'ORDER BY salary DESC, name ASC;', lang: 'sql' },
  { id: 'b_sql_distinct', pack: 'sql', topic: 'sql', level: 2, title: 'DISTINCT drops duplicates', blurb: 'It returns each unique row (or unique value, for a single column) — handy for "what values exist here?".', code: 'SELECT DISTINCT country\nFROM customers;', lang: 'sql' },
  { id: 'b_sql_limit', pack: 'sql', topic: 'sql', level: 1, title: 'LIMIT caps the rows', blurb: 'Return only the first N rows. Pair it with ORDER BY to get a real "top N".', code: 'SELECT name FROM players\nORDER BY score DESC\nLIMIT 10;', lang: 'sql' },
  { id: 'b_sql_null2', pack: 'sql', topic: 'sql', level: 2, title: 'Test NULL with IS, not =', blurb: "NULL means unknown, so NULL = NULL isn't true. Filter with IS NULL / IS NOT NULL.", code: 'WHERE manager_id IS NULL;', lang: 'sql' },
  { id: 'b_sql_alias', pack: 'sql', topic: 'sql', level: 2, title: 'AS renames a column or table', blurb: 'An alias gives a column a friendlier output name, or a table a short handle to use in joins.', code: 'SELECT salary * 12 AS annual_pay\nFROM employees AS e;', lang: 'sql' },
  { id: 'b_sql_groupby', pack: 'sql', topic: 'sql', level: 2, title: 'GROUP BY collapses rows into groups', blurb: 'One output row per group, with aggregates — COUNT, SUM, AVG, MIN, MAX — computed within each group.', code: 'SELECT dept, AVG(salary)\nFROM employees\nGROUP BY dept;', lang: 'sql' },
  { id: 'b_sql_having2', pack: 'sql', topic: 'sql', level: 3, title: 'HAVING filters groups', blurb: 'WHERE filters rows before grouping; HAVING filters the groups after — the only place an aggregate belongs in a filter.', code: 'GROUP BY dept\nHAVING COUNT(*) > 5;', lang: 'sql' },
  { id: 'b_sql_order_exec', pack: 'sql', topic: 'sql', level: 3, title: 'SQL runs in a different order than you write it', blurb: 'Logical order: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT. That is why a SELECT alias cannot be used back in WHERE.' },
  { id: 'b_sql_comment', pack: 'sql', topic: 'sql', level: 1, title: 'Comment with -- or /* */', blurb: '-- comments to the end of the line; /* … */ spans lines. Leave a note on the tricky bits.', code: '-- active users only\nWHERE active = 1; /* soft-deletes excluded */', lang: 'sql' },

  // ── Intermediate (level 2) ──────────────────────────────────────────
  { id: 'b_sql_innerjoin', pack: 'sql', topic: 'sql', level: 2, title: 'INNER JOIN keeps only matches', blurb: 'It returns rows where the ON condition matches in BOTH tables; unmatched rows on either side are dropped.', code: 'SELECT o.id, c.name\nFROM orders o\nJOIN customers c ON c.id = o.customer_id;', lang: 'sql' },
  { id: 'b_sql_jointypes', pack: 'sql', topic: 'sql', level: 2, title: 'Join types differ only in who survives', blurb: 'INNER = matches only. LEFT = all left rows. RIGHT = all right rows. FULL OUTER = all of both. The unmatched side fills with NULL.' },
  { id: 'b_sql_crossjoin', pack: 'sql', topic: 'sql', level: 2, title: 'CROSS JOIN pairs everything', blurb: 'Every row of A with every row of B — the Cartesian product, N×M rows. Usually a bug when it happens by accident (a forgotten ON).' },
  { id: 'b_sql_selfjoin', pack: 'sql', topic: 'sql', level: 2, title: 'A table can join itself', blurb: 'Alias it twice to relate rows within one table — an employee to their manager, say.', code: 'SELECT e.name, m.name AS manager\nFROM emp e\nJOIN emp m ON m.id = e.manager_id;', lang: 'sql' },
  { id: 'b_sql_aggregates', pack: 'sql', topic: 'sql', level: 2, title: 'Aggregates fold many rows into one', blurb: 'COUNT, SUM, AVG, MIN, MAX. With no GROUP BY they collapse the whole result to a single row.', code: 'SELECT COUNT(*), AVG(salary)\nFROM employees;', lang: 'sql' },
  { id: 'b_sql_case', pack: 'sql', topic: 'sql', level: 2, title: "CASE is SQL's if / else", blurb: 'Return a different value per row by condition. The first matching WHEN wins; ELSE is the fallback.', code: "SELECT name,\n  CASE WHEN score>=90 THEN 'A'\n       WHEN score>=80 THEN 'B'\n       ELSE 'C' END AS grade\nFROM exams;", lang: 'sql' },
  { id: 'b_sql_subquery', pack: 'sql', topic: 'sql', level: 2, title: 'A subquery is a query inside a query', blurb: 'Use its result in WHERE, SELECT, or FROM. Here it supplies the set for IN.', code: "SELECT name FROM employees\nWHERE dept_id IN (\n  SELECT id FROM depts WHERE region='EU');", lang: 'sql' },
  { id: 'b_sql_exists', pack: 'sql', topic: 'sql', level: 3, title: 'EXISTS checks for any match', blurb: 'True as soon as the subquery returns one row — often faster than IN for a correlated "has any" test.', code: 'SELECT u.name FROM users u\nWHERE EXISTS (\n  SELECT 1 FROM orders o WHERE o.uid = u.id);', lang: 'sql' },
  { id: 'b_sql_union', pack: 'sql', topic: 'sql', level: 2, title: 'UNION stacks results; ALL keeps dupes', blurb: 'UNION removes duplicate rows (and sorts to do it); UNION ALL keeps everything and is faster. Both need matching column counts and types.' },
  { id: 'b_sql_coalesce', pack: 'sql', topic: 'sql', level: 2, title: 'COALESCE returns the first non-NULL', blurb: "A clean default for missing values — it takes the first argument that isn't NULL.", code: "SELECT COALESCE(nickname, first_name, 'friend');", lang: 'sql' },
  { id: 'b_sql_nullif', pack: 'sql', topic: 'sql', level: 3, title: 'NULLIF guards division by zero', blurb: 'NULLIF(a, 0) turns 0 into NULL, so a / NULLIF(b, 0) yields NULL instead of an error.', code: 'SELECT wins * 1.0 / NULLIF(games, 0) AS win_rate;', lang: 'sql' },
  { id: 'b_sql_cast', pack: 'sql', topic: 'sql', level: 2, title: 'CAST converts types', blurb: 'Turn a string into a number, a timestamp into a date, and so on. Postgres also spells it value::type.', code: "SELECT CAST('2020-01-01' AS DATE),\n       CAST(qty AS REAL);", lang: 'sql' },
  { id: 'b_sql_strings', pack: 'sql', topic: 'sql', level: 2, title: 'The string toolkit', blurb: 'LENGTH, UPPER / LOWER, TRIM, SUBSTRING, and CONCAT (or the || operator) clean and reshape text.', code: "SELECT UPPER(TRIM(name)),\n       first || ' ' || last AS full;", lang: 'sql' },
  { id: 'b_sql_pagination', pack: 'sql', topic: 'sql', level: 2, title: 'LIMIT + OFFSET paginate', blurb: 'LIMIT 10 OFFSET 20 is page 3 at ten per page. Always pair with ORDER BY, or "page" has no stable meaning.', code: 'SELECT * FROM posts\nORDER BY created DESC\nLIMIT 10 OFFSET 20;', lang: 'sql' },

  // ── Advanced (level 3) ──────────────────────────────────────────────
  { id: 'b_sql_cte', pack: 'sql', topic: 'sql', level: 3, title: 'A CTE names a subquery', blurb: 'WITH gives a query block a name you can reuse, so a nested query reads top-to-bottom instead of inside-out.', code: 'WITH big AS (\n  SELECT dept, SUM(pay) t FROM emp GROUP BY dept)\nSELECT * FROM big WHERE t > 1000000;', lang: 'sql' },
  { id: 'b_sql_recursive', pack: 'sql', topic: 'sql', level: 3, title: 'Recursive CTEs walk hierarchies', blurb: 'WITH RECURSIVE builds on itself — org charts, graphs, number series: an anchor row, then a step that references the CTE until it stops.' },
  { id: 'b_sql_window', pack: 'sql', topic: 'sql', level: 3, title: 'Window functions keep every row', blurb: 'OVER() runs an aggregate or rank per row WITHOUT collapsing the result — unlike GROUP BY, nothing is folded away.', code: 'SELECT name, salary,\n  AVG(salary) OVER () AS company_avg\nFROM employees;', lang: 'sql' },
  { id: 'b_sql_partition', pack: 'sql', topic: 'sql', level: 3, title: 'PARTITION BY windows per group', blurb: 'Like GROUP BY, but for a window: it restarts the calculation for each partition while keeping the rows.', code: 'AVG(salary) OVER (PARTITION BY dept)', lang: 'sql' },
  { id: 'b_sql_ranks', pack: 'sql', topic: 'sql', level: 3, title: 'ROW_NUMBER vs RANK vs DENSE_RANK', blurb: 'ROW_NUMBER is always 1,2,3 (ties broken arbitrarily). RANK skips after a tie (1,1,3). DENSE_RANK does not (1,1,2).', code: 'ROW_NUMBER() OVER (ORDER BY score DESC)', lang: 'sql' },
  { id: 'b_sql_laglead', pack: 'sql', topic: 'sql', level: 3, title: 'LAG and LEAD peek at neighbours', blurb: "The previous or next row's value in the window — perfect for deltas over time.", code: 'salary - LAG(salary) OVER (ORDER BY hired)\n  AS raise;', lang: 'sql' },
  { id: 'b_sql_running', pack: 'sql', topic: 'sql', level: 3, title: 'Running totals with SUM OVER', blurb: 'An ordered window accumulates as it goes — a cumulative sum with no self-join.', code: 'SUM(amount) OVER (ORDER BY day) AS running', lang: 'sql' },
  { id: 'b_sql_btree', pack: 'sql', topic: 'sql', level: 3, title: 'Indexes are sorted shortcuts', blurb: 'A B-tree index turns a full table scan into a fast lookup for the columns you filter, join, or sort on — paid for with slower writes and storage. Index selectively.' },
  { id: 'b_sql_sargable', pack: 'sql', topic: 'sql', level: 3, title: 'Keep predicates sargable', blurb: 'Wrapping a column in a function — WHERE YEAR(d)=2020 — hides it from its index. Rewrite as a range so the index can be used.', code: "WHERE d >= '2020-01-01'\n  AND d <  '2021-01-01';", lang: 'sql' },
  { id: 'b_sql_explain', pack: 'sql', topic: 'sql', level: 3, title: 'EXPLAIN shows the plan', blurb: 'It reveals whether the engine uses an index or scans the whole table, and where the cost is. The first tool to reach for when a query is slow.', code: 'EXPLAIN ANALYZE\nSELECT * FROM orders WHERE uid = 42;', lang: 'sql' },
  { id: 'b_sql_transaction', pack: 'sql', topic: 'sql', level: 3, title: 'Transactions are all-or-nothing', blurb: 'BEGIN … COMMIT makes a group of writes atomic; ROLLBACK undoes them. ACID = Atomic, Consistent, Isolated, Durable.', code: 'BEGIN;\nUPDATE acct SET bal=bal-100 WHERE id=1;\nUPDATE acct SET bal=bal+100 WHERE id=2;\nCOMMIT;', lang: 'sql' },
  { id: 'b_sql_view', pack: 'sql', topic: 'sql', level: 3, title: 'A view is a saved query', blurb: 'SELECT from it like a table; it always reflects the live underlying data. Great for hiding complexity — a materialized view is the one that caches.', code: 'CREATE VIEW active_users AS\nSELECT * FROM users WHERE active = 1;', lang: 'sql' },
  { id: 'b_sql_selectstar', pack: 'sql', topic: 'sql', level: 2, title: 'SELECT * costs you', blurb: 'It fetches columns you do not need, breaks silently when the schema changes, and blocks index-only scans. Name the columns you actually use.' },
];

/* ── Python: basics → advanced ─────────────────────────────────────────── */
export const PYTHON_BYTES: Omit<ByteCard, 'updatedAt'>[] = [
  { id: 'b_py_dynamic', pack: 'python', topic: 'python', level: 1, title: 'Python is dynamically typed', blurb: "A variable is just a name bound to an object; the type belongs to the object and is checked at runtime — so one name can point at an int, then a string." },
  { id: 'b_py_listtuple', pack: 'python', topic: 'python', level: 1, title: 'List mutable, tuple immutable', blurb: "[] changes in place; () can't. Use a tuple for a fixed record or a dict key, a list for a growing collection.", code: 'pt = (3, 4)      # fixed\nxs = [1, 2, 3]   # grows', lang: 'python' },
  { id: 'b_py_dict', pack: 'python', topic: 'python', level: 1, title: 'Dicts map keys to values in O(1)', blurb: 'Backed by a hash table. dict.get(k, default) avoids a KeyError when the key is missing.', code: "ages = {'ana': 30}\nages.get('bob', 0)  # 0", lang: 'python' },
  { id: 'b_py_set', pack: 'python', topic: 'python', level: 1, title: 'Sets are unique and fast to search', blurb: 'Unordered, no duplicates, O(1) membership — perfect for dedup and "have I seen this?" checks.', code: 'seen = set()\nif x not in seen:\n    seen.add(x)', lang: 'python' },
  { id: 'b_py_fstring', pack: 'python', topic: 'python', level: 1, title: 'f-strings format inline', blurb: 'Drop expressions straight into the string; :.2f, :, and friends format numbers.', code: "f'{name}: {price:.2f}'", lang: 'python' },
  { id: 'b_py_truthy', pack: 'python', topic: 'python', level: 1, title: 'Empty is falsy', blurb: "0, '', [], {} and None all count as False in an if — so `if xs:` reads as 'if non-empty'." },
  { id: 'b_py_slice', pack: 'python', topic: 'python', level: 1, title: 'Slicing takes a range', blurb: 'xs[start:stop:step], stop excluded. xs[::-1] reverses; xs[:] makes a copy.', code: 'xs[1:4]    # items 1,2,3\nxs[::-1]   # reversed', lang: 'python' },
  { id: 'b_py_argskwargs', pack: 'python', topic: 'python', level: 2, title: '*args and **kwargs catch the rest', blurb: '*args gathers extra positionals into a tuple; **kwargs gathers keyword arguments into a dict.', code: 'def f(*args, **kwargs):\n    print(args, kwargs)', lang: 'python' },
  { id: 'b_py_unpack', pack: 'python', topic: 'python', level: 2, title: 'Unpack with * to grab the middle', blurb: 'a, *mid, b = xs binds the ends and collects everything between them into a list.', code: 'first, *rest = [1, 2, 3, 4]\n# first=1, rest=[2,3,4]', lang: 'python' },
  { id: 'b_py_lambda', pack: 'python', topic: 'python', level: 2, title: 'Lambdas are one-line functions', blurb: 'Handy as a key= or with map/filter. If it needs a name or more than a line, write a def.', code: 'sorted(words, key=lambda w: len(w))', lang: 'python' },
  { id: 'b_py_exceptions', pack: 'python', topic: 'python', level: 2, title: 'try / except / else / finally', blurb: 'except catches, else runs when there was no error, finally always runs (cleanup). Catch specific types, not a bare except.', code: 'try: risky()\nexcept ValueError as e: log(e)\nfinally: close()', lang: 'python' },
  { id: 'b_py_decorator', pack: 'python', topic: 'python', level: 2, title: 'A decorator wraps a function', blurb: '@dec replaces f with dec(f) — add logging, timing or caching without touching the body.', code: '@lru_cache\ndef fib(n): ...', lang: 'python' },
  { id: 'b_py_zip', pack: 'python', topic: 'python', level: 2, title: 'zip walks lists in lockstep', blurb: 'It pairs items by position and stops at the shortest. dict(zip(keys, vals)) builds a dict.', code: 'for name, age in zip(names, ages):\n    ...', lang: 'python' },
  { id: 'b_py_gil', pack: 'python', topic: 'python', level: 3, title: 'The GIL serialises Python threads', blurb: 'Only one thread runs Python bytecode at a time. Threads still help I/O-bound work (they release the GIL while waiting); for CPU-bound work, use multiprocessing.' },
  { id: 'b_py_async', pack: 'python', topic: 'python', level: 3, title: 'async / await is cooperative I/O', blurb: 'An async function hands control back at each await, so one thread juggles thousands of waits (sockets, HTTP). It does not speed up CPU work.', code: 'async def get(u):\n    return await client.fetch(u)', lang: 'python' },
  { id: 'b_py_dunder', pack: 'python', topic: 'python', level: 3, title: 'Dunder methods hook the syntax', blurb: '__len__ powers len(x), __eq__ powers ==, __getitem__ powers x[i]. Implement them and your object behaves like a built-in.', code: 'def __repr__(self):\n    return f"Point({self.x}, {self.y})"', lang: 'python' },
  { id: 'b_py_property', pack: 'python', topic: 'python', level: 3, title: '@property makes a method look like a field', blurb: 'Compute a value on access, or validate on assignment, without changing the call site.', code: '@property\ndef area(self):\n    return self.w * self.h', lang: 'python' },
  { id: 'b_py_dataclass', pack: 'python', topic: 'python', level: 3, title: '@dataclass writes the boilerplate', blurb: 'It generates __init__, __repr__ and __eq__ from typed fields — a record without the ceremony.', code: '@dataclass\nclass Point:\n    x: int\n    y: int', lang: 'python' },
  { id: 'b_py_copy', pack: 'python', topic: 'python', level: 3, title: 'Shallow copy shares the insides', blurb: 'list(xs) or xs[:] copies the outer list but keeps the SAME inner objects. copy.deepcopy() clones all the way down.' },
  { id: 'b_py_gc', pack: 'python', topic: 'python', level: 3, title: 'Python frees memory by reference counting', blurb: 'An object is freed the moment its reference count hits zero; a separate cyclic collector sweeps up reference cycles. You rarely free by hand.' },
];

/* ── Algorithms & data structures: basics → advanced ───────────────────── */
export const ALGO_BYTES: Omit<ByteCard, 'updatedAt'>[] = [
  { id: 'b_algo_bigo', pack: 'algorithms', topic: 'algo', level: 1, title: 'Big-O measures growth, not seconds', blurb: 'It is how the work scales with input size, dropping constants. O(1) < O(log n) < O(n) < O(n log n) < O(n²) < O(2ⁿ).' },
  { id: 'b_algo_array', pack: 'algorithms', topic: 'algo', level: 1, title: 'Arrays index in O(1), insert in O(n)', blurb: 'Contiguous memory makes x[i] instant, but inserting in the middle shifts everything after it.' },
  { id: 'b_algo_linked', pack: 'algorithms', topic: 'algo', level: 1, title: 'Linked lists insert in O(1), index in O(n)', blurb: 'Each node points to the next, so splicing is cheap — but there is no jumping; you walk from the head.' },
  { id: 'b_algo_stackqueue', pack: 'algorithms', topic: 'algo', level: 1, title: 'Stack is LIFO, queue is FIFO', blurb: 'A stack pushes and pops the same end (undo, DFS, call stack); a queue adds at the back and removes at the front (scheduling, BFS).' },
  { id: 'b_algo_binsearch', pack: 'algorithms', topic: 'algo', level: 2, title: 'Binary search halves a sorted list', blurb: 'Check the middle, throw away half, repeat — O(log n). The list MUST be sorted.', code: 'while lo <= hi:\n    mid = (lo + hi) // 2\n    if a[mid] < t: lo = mid + 1\n    else: hi = mid - 1', lang: 'python' },
  { id: 'b_algo_twoptr', pack: 'algorithms', topic: 'algo', level: 2, title: 'Two pointers sweep from both ends', blurb: 'On a sorted array, move a left and right pointer inward — pair sums, palindromes, dedup, all in O(n).', code: 'l, r = 0, len(a) - 1\nwhile l < r:\n    ...', lang: 'python' },
  { id: 'b_algo_sliding', pack: 'algorithms', topic: 'algo', level: 2, title: 'Sliding window reuses work', blurb: 'Grow and shrink a window over a sequence instead of re-scanning — longest substring, max subarray, all in O(n).' },
  { id: 'b_algo_sort', pack: 'algorithms', topic: 'algo', level: 2, title: 'Comparison sorts bottom out at O(n log n)', blurb: 'Merge sort is stable and uses O(n) space; quicksort is in-place but O(n²) worst case. Counting/radix beat the bound only for bounded keys.' },
  { id: 'b_algo_recursion', pack: 'algorithms', topic: 'algo', level: 2, title: 'Recursion = base case + smaller subproblem', blurb: 'Every call must move toward a base case or it never stops, and each open call sits on the call stack.', code: 'def fac(n):\n    return 1 if n <= 1 else n * fac(n - 1)', lang: 'python' },
  { id: 'b_algo_bst', pack: 'algorithms', topic: 'algo', level: 2, title: 'A BST keeps things sorted', blurb: 'left < node < right, so search and insert average O(log n) — but degrade to O(n) if it becomes a chain. Balanced trees (AVL, red-black) prevent that.' },
  { id: 'b_algo_traversal', pack: 'algorithms', topic: 'algo', level: 2, title: 'Tree traversal: BFS vs DFS', blurb: 'BFS visits level by level with a queue; DFS goes deep first with a stack or recursion. Pre / in / post order differ only by when you visit the node.' },
  { id: 'b_algo_heap', pack: 'algorithms', topic: 'algo', level: 2, title: 'A heap gives the min or max in O(log n)', blurb: 'A binary heap keeps the smallest (or largest) at the root — the engine behind priority queues and "top K".', code: 'import heapq\nheapq.heappush(h, x)\nheapq.heappop(h)   # smallest', lang: 'python' },
  { id: 'b_algo_graph', pack: 'algorithms', topic: 'algo', level: 2, title: 'Graphs: adjacency list vs matrix', blurb: 'A list (dict of neighbours) is compact for sparse graphs; a matrix costs O(V²) space but checks an edge in O(1).' },
  { id: 'b_algo_bfs', pack: 'algorithms', topic: 'algo', level: 2, title: 'BFS finds the shortest unweighted path', blurb: 'Explore outward level by level with a queue; the first time you reach a node is the fewest edges away.' },
  { id: 'b_algo_dp', pack: 'algorithms', topic: 'algo', level: 3, title: 'DP trades memory for repeated work', blurb: 'When subproblems overlap, solve each once and store it — memoise top-down or fill a table bottom-up. Fibonacci, knapsack, edit distance.' },
  { id: 'b_algo_greedy', pack: 'algorithms', topic: 'algo', level: 3, title: 'Greedy takes the best local step', blurb: 'Pick the locally optimal choice and never look back. It only reaches the global optimum when the problem has the right structure (interval scheduling, Huffman).' },
  { id: 'b_algo_backtrack', pack: 'algorithms', topic: 'algo', level: 3, title: 'Backtracking tries, then undoes', blurb: 'Build a solution one choice at a time; when a partial choice cannot work, undo it and try the next — permutations, N-queens, sudoku.' },
  { id: 'b_algo_dijkstra', pack: 'algorithms', topic: 'algo', level: 3, title: 'Dijkstra: shortest path with weights', blurb: 'A BFS that uses a priority queue to always expand the cheapest frontier node. Requires non-negative edge weights.' },
  { id: 'b_algo_dsu', pack: 'algorithms', topic: 'algo', level: 3, title: 'Union-Find tracks connected groups', blurb: 'union() merges two sets, find() names a set — near O(1) with path compression. It detects cycles and builds MSTs (Kruskal).' },
  { id: 'b_algo_trie', pack: 'algorithms', topic: 'algo', level: 3, title: 'A trie stores strings by prefix', blurb: 'Each node is a character and shared prefixes share a path — autocomplete and prefix search in O(word length).' },
  { id: 'b_algo_topo', pack: 'algorithms', topic: 'algo', level: 3, title: 'Topological sort orders dependencies', blurb: 'A linear order of a DAG where every edge points forward — build order, task scheduling. It exists only if there is no cycle.' },
];

/* ── ML: intermediate → advanced (adds to the foundations ML cards) ─────── */
export const ML_BYTES: Omit<ByteCard, 'updatedAt'>[] = [
  { id: 'b_ml_split', pack: 'ml', topic: 'ml', level: 1, title: 'Split the data three ways', blurb: 'Train to fit, validation to tune, test to judge — once. Touch the test set while tuning and your score becomes a lie.' },
  { id: 'b_ml_crossval', pack: 'ml', topic: 'ml', level: 2, title: 'Cross-validation reuses the data', blurb: 'k-fold rotates which slice is held out and averages k scores — a sturdier estimate than one split, especially on small data.' },
  { id: 'b_ml_reg', pack: 'ml', topic: 'ml', level: 2, title: 'L1 and L2 punish big weights', blurb: 'Regularisation adds a weight penalty to the loss. L2 (ridge) shrinks smoothly; L1 (lasso) drives some weights to exactly 0, selecting features.' },
  { id: 'b_ml_loss', pack: 'ml', topic: 'ml', level: 2, title: 'Pick the loss for the task', blurb: 'MSE for regression, cross-entropy for classification. The loss is what training actually minimises — match it to what you care about.' },
  { id: 'b_ml_precrecall', pack: 'ml', topic: 'ml', level: 2, title: 'Precision vs recall', blurb: 'Precision: of the ones you flagged, how many were right. Recall: of the real ones, how many you caught. Spam and cancer weight them differently.' },
  { id: 'b_ml_f1', pack: 'ml', topic: 'ml', level: 2, title: 'F1 balances precision and recall', blurb: 'The harmonic mean of the two — high only when BOTH are high. More honest than accuracy on imbalanced classes.' },
  { id: 'b_ml_roc', pack: 'ml', topic: 'ml', level: 3, title: 'ROC-AUC scores ranking, not a cutoff', blurb: 'It sweeps every threshold, plotting true-positive vs false-positive rate. AUC 0.5 is a coin flip, 1.0 is perfect separation.' },
  { id: 'b_ml_confusion', pack: 'ml', topic: 'ml', level: 2, title: 'The confusion matrix shows the mistakes', blurb: 'TP, FP, FN, TN in one grid — every classification metric (accuracy, precision, recall) is just a ratio of its cells.' },
  { id: 'b_ml_scaling', pack: 'ml', topic: 'ml', level: 2, title: 'Scale features for distance and gradient models', blurb: 'If one feature runs 0–1 and another 0–100000, it dominates. Standardise or min-max — trees do not care, but KNN, SVM and neural nets do.' },
  { id: 'b_ml_onehot', pack: 'ml', topic: 'ml', level: 2, title: 'One-hot encodes categories', blurb: "Turn a category into a row of 0/1 columns so the model doesn't read 'red=1, blue=2' as an ordering.", code: 'blue → [0, 1, 0]', lang: 'text' },
  { id: 'b_ml_optimizers', pack: 'ml', topic: 'ml', level: 3, title: 'SGD, momentum, Adam', blurb: 'Plain SGD steps by the gradient; momentum carries velocity through flat spots; Adam adapts a per-parameter step size and usually just works.' },
  { id: 'b_ml_vanishing', pack: 'ml', topic: 'ml', level: 3, title: 'Vanishing and exploding gradients', blurb: 'In deep nets, gradients multiply through layers and shrink to 0 or blow up. ReLU, residual connections and normalisation keep them alive.' },
  { id: 'b_ml_batchnorm', pack: 'ml', topic: 'ml', level: 3, title: 'Batch norm steadies training', blurb: "It normalises each layer's inputs per mini-batch, so you can use higher learning rates and train deeper nets faster." },
  { id: 'b_ml_pca', pack: 'ml', topic: 'ml', level: 3, title: 'PCA compresses along the biggest variance', blurb: 'It finds new axes (principal components) that capture the most spread, so you keep a few and drop the rest — reduction and visualisation.' },
  { id: 'b_ml_kmeans', pack: 'ml', topic: 'ml', level: 2, title: 'k-means clusters by nearest centroid', blurb: 'Pick k centres, assign each point to the closest, move each centre to its points’ mean, repeat. You choose k; it finds the groups.' },
  { id: 'b_ml_tree', pack: 'ml', topic: 'ml', level: 2, title: 'Decision trees split on questions', blurb: 'Each node asks a yes/no on one feature; leaves are predictions. Readable — but a deep tree overfits.' },
  { id: 'b_ml_forest', pack: 'ml', topic: 'ml', level: 2, title: 'Random forests vote', blurb: 'Many trees on random subsets of rows and features, averaged — bagging cuts the variance a single tree suffers.' },
  { id: 'b_ml_boosting', pack: 'ml', topic: 'ml', level: 3, title: 'Boosting fixes its own mistakes', blurb: 'Trees added in sequence, each focused on the errors of the last (XGBoost, LightGBM). Often the winner on tabular data.' },
  { id: 'b_ml_cnn', pack: 'ml', topic: 'ml', level: 3, title: 'CNNs slide filters over grids', blurb: 'A convolution reuses one small filter across an image, learning edges → shapes → objects with far fewer weights than a dense net.' },
  { id: 'b_ml_transfer', pack: 'ml', topic: 'ml', level: 3, title: 'Transfer learning reuses a trained model', blurb: 'Start from a big pretrained model and fine-tune on your small dataset — you inherit its features instead of learning from scratch.' },
];

/* ── AI / LLMs: adds to the foundations AI cards ────────────────────────── */
export const AI_BYTES: Omit<ByteCard, 'updatedAt'>[] = [
  { id: 'b_ai_context', pack: 'ai', topic: 'ai', level: 1, title: 'The context window is working memory', blurb: 'Everything the model sees at once — prompt, history, retrieved docs — measured in tokens. Past the limit, the oldest falls off.' },
  { id: 'b_ai_prompt', pack: 'ai', topic: 'ai', level: 1, title: 'Prompting is programming in English', blurb: 'Be specific, state the format you want, show an example. Clear instructions beat clever tricks.' },
  { id: 'b_ai_system', pack: 'ai', topic: 'ai', level: 1, title: 'The system prompt sets the rules', blurb: "A high-priority instruction that frames the model's role and boundaries for the whole conversation, above the user's turns." },
  { id: 'b_ai_fewshot', pack: 'ai', topic: 'ai', level: 2, title: 'Few-shot = teach by examples', blurb: 'Put a couple of input→output examples in the prompt and the model imitates the pattern — no training needed (in-context learning).' },
  { id: 'b_ai_cot', pack: 'ai', topic: 'ai', level: 2, title: 'Chain-of-thought = ask it to reason', blurb: 'Telling the model to work step by step before answering improves hard reasoning, because each step conditions the next.' },
  { id: 'b_ai_rag', pack: 'ai', topic: 'ai', level: 2, title: 'RAG grounds answers in your data', blurb: 'Retrieve relevant documents, put them in the prompt, then answer FROM them — cuts hallucination and adds fresh, private knowledge without retraining.' },
  { id: 'b_ai_embed', pack: 'ai', topic: 'ai', level: 2, title: 'Embeddings turn text into vectors', blurb: "Similar meanings land near each other in vector space, so nearest-neighbour search becomes semantic search — the engine behind RAG." },
  { id: 'b_ai_topp', pack: 'ai', topic: 'ai', level: 2, title: 'top-p and top-k trim the choices', blurb: 'Beyond temperature, sample only from the top-k tokens or the smallest set covering probability p — fewer wild picks.' },
  { id: 'b_ai_pretrain', pack: 'ai', topic: 'ai', level: 2, title: 'Pretraining, then fine-tuning', blurb: 'First learn language from a huge corpus (self-supervised next-token), then specialise on a smaller labelled set. Most of the knowledge is in stage one.' },
  { id: 'b_ai_finetune', pack: 'ai', topic: 'ai', level: 3, title: 'Fine-tune vs prompt', blurb: 'Prompting and RAG change what the model SEES; fine-tuning changes its WEIGHTS. Fine-tune for style and format at scale — for facts, reach for RAG.' },
  { id: 'b_ai_rlhf', pack: 'ai', topic: 'ai', level: 3, title: 'RLHF aligns to human preference', blurb: 'After pretraining, the model is tuned on human rankings of its answers, so it becomes helpful and follows instructions — not just a next-token predictor.' },
  { id: 'b_ai_agents', pack: 'ai', topic: 'ai', level: 3, title: 'Agents call tools in a loop', blurb: 'Give the model tools (search, code, APIs) and let it decide, act, observe the result, and repeat — reasoning plus doing.' },
  { id: 'b_ai_diffusion', pack: 'ai', topic: 'ai', level: 3, title: 'Diffusion models denoise into images', blurb: 'Train a net to remove a little noise, then run it backwards from pure noise step by step until an image appears — the idea behind Stable Diffusion.' },
  { id: 'b_ai_quant', pack: 'ai', topic: 'ai', level: 3, title: 'Quantisation shrinks the model', blurb: 'Store weights in 8- or 4-bit instead of 16/32, cutting memory and speeding inference for a small accuracy hit — how big models run on a laptop.' },
];

/* ── CS fundamentals: adds to the foundations CS cards ──────────────────── */
export const CS_BYTES: Omit<ByteCard, 'updatedAt'>[] = [
  { id: 'b_cs_status', pack: 'cs', topic: 'cs', level: 1, title: 'HTTP status codes by the hundreds', blurb: '2xx success, 3xx redirect, 4xx you messed up (404 not found, 401 unauthorised), 5xx the server did.' },
  { id: 'b_cs_http', pack: 'cs', topic: 'cs', level: 1, title: 'HTTP verbs say what you are doing', blurb: 'GET reads, POST creates, PUT/PATCH updates, DELETE removes. GET and DELETE should be idempotent; POST usually is not.' },
  { id: 'b_cs_dns', pack: 'cs', topic: 'cs', level: 1, title: 'DNS is the internet phone book', blurb: 'It turns a name (example.com) into an IP address, cached at many layers so it is fast — the first step of almost every request.' },
  { id: 'b_cs_stackheap', pack: 'cs', topic: 'cs', level: 2, title: 'Stack memory vs heap memory', blurb: 'The stack holds call frames and locals (fast, freed automatically on return); the heap holds objects that outlive a call. Deep recursion overflows the stack.' },
  { id: 'b_cs_procthread', pack: 'cs', topic: 'cs', level: 2, title: 'Processes are isolated; threads share', blurb: 'Each process has its own memory; threads inside one share it — cheaper to switch, but you must guard shared state with locks against races.' },
  { id: 'b_cs_concpar', pack: 'cs', topic: 'cs', level: 2, title: 'Concurrency vs parallelism', blurb: 'Concurrency is dealing with many things at once (interleaving); parallelism is doing many at once (multiple cores). You can have either without the other.' },
  { id: 'b_cs_tcpudp', pack: 'cs', topic: 'cs', level: 2, title: 'TCP is reliable, UDP is fast', blurb: 'TCP guarantees ordered, retried delivery (web, files); UDP just fires packets and forgets (games, video, DNS) — no handshake, no resend.' },
  { id: 'b_cs_rest', pack: 'cs', topic: 'cs', level: 2, title: 'REST models URLs as resources', blurb: 'Nouns as paths (/users/42), verbs as HTTP methods, stateless requests. Predictable and cacheable.' },
  { id: 'b_cs_cache', pack: 'cs', topic: 'cs', level: 2, title: 'Caching trades freshness for speed', blurb: 'Keep a copy close (memory, CDN) so you do not recompute or refetch. The hard parts are invalidation and staleness.' },
  { id: 'b_cs_latency', pack: 'cs', topic: 'cs', level: 2, title: 'Know the latency ladder', blurb: 'Roughly: RAM ~100ns, SSD ~100µs, a network round-trip ~1–100ms. Each rung is about 1000× slower — design to stay on the fast ones.' },
  { id: 'b_cs_acid', pack: 'cs', topic: 'cs', level: 2, title: 'ACID is a transaction promise', blurb: 'Atomic (all or nothing), Consistent (valid state), Isolated (as if alone), Durable (survives a crash). SQL databases give you this.' },
  { id: 'b_cs_cap', pack: 'cs', topic: 'cs', level: 3, title: 'CAP: pick two under a partition', blurb: 'When the network splits, a distributed store can stay Consistent or Available, not both. Most choose availability plus eventual consistency.' },
  { id: 'b_cs_loadbalance', pack: 'cs', topic: 'cs', level: 2, title: 'Load balancers spread traffic', blurb: 'One entry point fans requests across many servers (round-robin, least-connections), so you scale out and survive a node dying.' },
  { id: 'b_cs_compinterp', pack: 'cs', topic: 'cs', level: 2, title: 'Compiled vs interpreted', blurb: 'A compiler translates the whole program to machine code ahead of time (C, Rust — fast); an interpreter runs it line by line (Python — flexible). A JIT does both.' },
  { id: 'b_cs_gc', pack: 'cs', topic: 'cs', level: 2, title: 'Garbage collection frees unused memory', blurb: 'The runtime finds objects nothing points at and reclaims them, so you do not free by hand — at the cost of occasional pauses.' },
  { id: 'b_cs_unicode', pack: 'cs', topic: 'cs', level: 2, title: 'UTF-8 encodes every character', blurb: 'Unicode gives each character a number; UTF-8 stores it in 1–4 bytes and stays ASCII-compatible. Length in bytes is not length in characters.' },
];

/*
 * The SQL Tutorial pack — a full basics → intermediate → advanced curriculum,
 * mapped one concept at a time from a personal study set. Original flashcard
 * phrasing (concept → title + intuition + tiny example), not tutorial prose.
 * ids `b_sqt_*`; topic 'sql'; level 1 basic · 2 intermediate · 3 advanced.
 */
export const SQL_TUTORIAL_BYTES: Omit<ByteCard, 'updatedAt'>[] = [
  // ── basics ──
  { id: 'b_sqt_rdbms', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'SQL runs on a relational database', blurb: 'An RDBMS stores data as tables of typed rows and columns with keys. SQL is how you query it — declarative: you say what you want, not how to fetch it.' },
  { id: 'b_sqt_flavors', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'One SQL, many dialects', blurb: 'PostgreSQL, MySQL, SQLite and SQL Server share a common core but differ in functions and quirks. Learn one (PostgreSQL is a solid default) and the rest transfer.' },
  { id: 'b_sqt_select', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'SELECT names the columns', blurb: 'List the columns you want and the table to read from. The database hands back a result set — a table of just those columns.', code: 'SELECT first_name, salary\nFROM employees;', lang: 'sql' },
  { id: 'b_sqt_trailingcomma', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'The trailing-comma error', blurb: 'A comma after the last column before FROM is a syntax error — SQL expects another column name. It bites when you delete the final field.', code: 'SELECT name, salary,   -- stray comma\nFROM employees;', lang: 'sql' },
  { id: 'b_sqt_selectstar', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'SELECT * is convenient, not clean', blurb: '* returns every column — fine while exploring, but wasteful and fragile in real queries. Name the columns you actually use.', code: 'SELECT * FROM employees;   -- exploring only', lang: 'sql' },
  { id: 'b_sqt_where_ops', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'WHERE compares with operators', blurb: "= equals, <> (or !=) not-equals, and < <= > >= for ordering. Strings and dates go in single quotes.", code: "SELECT *\nFROM orders\nWHERE total >= 100 AND status <> 'void';", lang: 'sql' },
  { id: 'b_sqt_andornot', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'AND binds tighter than OR', blurb: 'In a mixed condition AND is evaluated before OR — so wrap OR groups in parentheses to get the logic you mean.', code: "WHERE country = 'US'\n  AND (plan = 'pro' OR plan = 'team');", lang: 'sql' },
  { id: 'b_sqt_notbetween', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'NOT negates a condition', blurb: 'Put NOT before a predicate to flip it: NOT IN, NOT LIKE, NOT BETWEEN — it keeps the rows the plain version would drop.', code: 'WHERE age NOT BETWEEN 18 AND 30;', lang: 'sql' },
  { id: 'b_sqt_between', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'BETWEEN includes both ends', blurb: "x BETWEEN a AND b means a <= x <= b — both bounds count. Careful with timestamps: an end at midnight excludes that whole day.", code: "WHERE hired BETWEEN '2024-01-01' AND '2024-12-31';", lang: 'sql' },
  { id: 'b_sqt_in', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'IN is OR, shortened', blurb: 'value IN (a, b, c) matches any item in the list — cleaner than chaining ORs. The list can even be a subquery.', code: "WHERE country IN ('US', 'CA', 'MX');", lang: 'sql' },
  { id: 'b_sqt_like', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'LIKE matches patterns', blurb: "% is any run of characters, _ is exactly one. 'A%' starts with A; '%@gmail.com' ends with it; '_a%' has a as the 2nd char.", code: "WHERE email LIKE '%@gmail.com';", lang: 'sql' },
  { id: 'b_sqt_filter5', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'Five ways to filter in WHERE', blurb: 'Comparisons (=, >), BETWEEN for ranges, IN for lists, LIKE for patterns, and AND/OR/NOT to combine. Most filters are a mix of these five.' },
  { id: 'b_sqt_orderby', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'ORDER BY sorts the result', blurb: 'Ascending by default; add DESC for high-to-low. List several keys to break ties left to right.', code: 'ORDER BY dept ASC, salary DESC;', lang: 'sql' },
  { id: 'b_sqt_orderby_num', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'ORDER BY can use column position', blurb: "ORDER BY 2 sorts by the 2nd selected column — handy for expressions you'd rather not retype, though names read clearer.", code: 'SELECT dept, COUNT(*)\nFROM emp GROUP BY dept\nORDER BY 2 DESC;', lang: 'sql' },
  { id: 'b_sqt_limit_offset', pack: 'sql-tutorial', topic: 'sql', level: 1, title: 'LIMIT caps rows, OFFSET skips them', blurb: 'LIMIT n returns the first n rows after sorting; OFFSET m skips m first. Together they page through results.', code: 'ORDER BY score DESC\nLIMIT 10 OFFSET 20;   -- page 3', lang: 'sql' },
  // ── intermediate ──
  { id: 'b_sqt_count', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'COUNT(*) vs COUNT(col)', blurb: 'COUNT(*) counts rows. COUNT(col) counts only rows where col is not NULL. COUNT(DISTINCT col) counts unique non-null values.', code: 'SELECT COUNT(*), COUNT(DISTINCT dept)\nFROM employees;', lang: 'sql' },
  { id: 'b_sqt_sumavg', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'SUM and AVG ignore NULLs', blurb: 'Aggregates skip NULLs — so AVG divides by the count of non-null values, not total rows. COALESCE to 0 first if you want them counted.', code: 'SELECT SUM(amount), AVG(amount)\nFROM sales;', lang: 'sql' },
  { id: 'b_sqt_minmax', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'MIN and MAX work on any orderable type', blurb: 'Smallest and largest — numbers, dates, even text (alphabetical). The go-to for earliest/latest date or cheapest/priciest item.', code: 'SELECT MIN(hired), MAX(salary)\nFROM employees;', lang: 'sql' },
  { id: 'b_sqt_groupby', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'GROUP BY collapses rows into buckets', blurb: 'It folds rows sharing a value into one group, so aggregates run per group instead of over the whole table.', code: 'SELECT dept, AVG(salary)\nFROM employees\nGROUP BY dept;', lang: 'sql' },
  { id: 'b_sqt_groupby_rule', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'Every plain column must be grouped', blurb: "In a GROUP BY query each selected column is either in GROUP BY or inside an aggregate — otherwise which row's value would it show?" },
  { id: 'b_sqt_having', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'HAVING filters groups, WHERE filters rows', blurb: "WHERE runs before grouping (no aggregates allowed); HAVING runs after, on the grouped result — that's where COUNT(*) > 5 goes.", code: 'GROUP BY dept\nHAVING COUNT(*) > 5;', lang: 'sql' },
  { id: 'b_sqt_distinct', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'DISTINCT dedupes whole rows', blurb: 'It dedupes across ALL selected columns, not just the first — SELECT DISTINCT a, b keeps unique (a, b) pairs.', code: 'SELECT DISTINCT city, country\nFROM customers;', lang: 'sql' },
  { id: 'b_sqt_arithmetic', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'Compute new columns inline', blurb: '+, -, *, / work on columns row by row. Name the result with AS so it has a clean header.', code: 'SELECT price * quantity AS revenue\nFROM line_items;', lang: 'sql' },
  { id: 'b_sqt_intdiv', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'Integer / integer truncates', blurb: '5 / 2 is 2, not 2.5 — dividing two integers drops the remainder. Cast one side to decimal for real division.', code: 'SELECT wins * 1.0 / games AS win_rate\nFROM teams;', lang: 'sql' },
  { id: 'b_sqt_mathfns', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'The everyday math functions', blurb: "ROUND(x, d), CEIL/FLOOR, ABS, POWER(b, e), SQRT, and MOD(a, b) for remainder. ROUND's second arg is decimal places.", code: 'SELECT ROUND(avg_score, 1), MOD(id, 2)\nFROM results;', lang: 'sql' },
  { id: 'b_sqt_null', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'NULL is contagious', blurb: 'Any arithmetic or comparison with NULL yields NULL, not true/false. Test membership with IS NULL / IS NOT NULL only.', code: 'WHERE manager_id IS NULL;', lang: 'sql' },
  { id: 'b_sqt_coalesce', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'COALESCE picks the first non-NULL', blurb: "COALESCE(a, b, c) returns the first argument that isn't NULL — the clean way to supply a default for missing data.", code: "SELECT COALESCE(nickname, first_name, 'friend')\nFROM users;", lang: 'sql' },
  { id: 'b_sqt_case', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'CASE is if/else in SQL', blurb: 'It returns a value per row, testing conditions top to bottom and stopping at the first match; ELSE catches the rest.', code: "SELECT name,\n  CASE WHEN score >= 90 THEN 'A'\n       WHEN score >= 80 THEN 'B'\n       ELSE 'C' END AS grade\nFROM exams;", lang: 'sql' },
  { id: 'b_sqt_innerjoin', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'INNER JOIN keeps only matches', blurb: 'It returns rows that pair up on the join key in both tables; unmatched rows on either side are dropped.', code: 'SELECT o.id, c.name\nFROM orders o\nJOIN customers c ON c.id = o.customer_id;', lang: 'sql' },
  { id: 'b_sqt_leftright', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'LEFT/RIGHT JOIN keep one side whole', blurb: 'LEFT JOIN keeps every left row, NULL-filling missing right matches (RIGHT is the mirror). WHERE right.key IS NULL finds non-matches.', code: 'FROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id;', lang: 'sql' },
  { id: 'b_sqt_fullouter', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'FULL OUTER JOIN keeps both sides', blurb: "Every row from left and right appears; wherever there's no match, the other side is NULL. Use it to reconcile two sets.", code: 'FROM a\nFULL OUTER JOIN b ON a.id = b.id;', lang: 'sql' },
  { id: 'b_sqt_datetime', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'Dates do math', blurb: 'CURRENT_DATE / NOW() give today; subtract two dates for an interval; add time with INTERVAL. AGE(a, b) gives a human-readable gap.', code: "WHERE created > NOW() - INTERVAL '7 days';", lang: 'sql' },
  { id: 'b_sqt_dateextract', pack: 'sql-tutorial', topic: 'sql', level: 2, title: 'EXTRACT and DATE_TRUNC bucket time', blurb: "EXTRACT(YEAR FROM d) pulls one part; DATE_TRUNC('month', d) floors a timestamp to the start of its month — the key to time-series grouping.", code: "SELECT DATE_TRUNC('month', created) AS m, COUNT(*)\nFROM signups GROUP BY m;", lang: 'sql' },
  // ── advanced ──
  { id: 'b_sqt_cte', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'A CTE names a subquery', blurb: 'WITH t AS (...) defines a temporary, named result you SELECT from below — reads top-to-bottom like steps, far clearer than deep nesting.', code: 'WITH big AS (\n  SELECT * FROM sales WHERE amount > 1000\n)\nSELECT region, COUNT(*) FROM big GROUP BY region;', lang: 'sql' },
  { id: 'b_sqt_subquery', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'A subquery is a query inside a query', blurb: 'It can feed a value to WHERE (scalar), a list to IN, or a whole table to FROM. Inline and one-off — great when you use it once.', code: 'WHERE salary > (SELECT AVG(salary) FROM employees);', lang: 'sql' },
  { id: 'b_sqt_cte_vs_sub', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'CTE vs subquery: clarity vs locality', blurb: 'Reach for a CTE when the logic repeats or the query is deep — it names each step. A subquery wins for a quick, single, inline use.' },
  { id: 'b_sqt_window_over', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'Window functions compute without collapsing', blurb: 'OVER(...) runs an aggregate across a set of rows while keeping every row — so you get the total AND each row beside it.', code: 'SELECT name, salary,\n  AVG(salary) OVER () AS company_avg\nFROM employees;', lang: 'sql' },
  { id: 'b_sqt_partitionby', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'PARTITION BY is GROUP BY for windows', blurb: 'It restarts the window per group, so the aggregate is computed within each partition but the rows stay intact.', code: 'AVG(salary) OVER (PARTITION BY dept)', lang: 'sql' },
  { id: 'b_sqt_runningsum', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'ORDER BY in a window = running total', blurb: 'Adding ORDER BY inside OVER accumulates row by row, giving a running sum (or any moving metric) up to each row.', code: 'SUM(amount) OVER (ORDER BY day) AS running_total', lang: 'sql' },
  { id: 'b_sqt_firstlast', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'LAST_VALUE needs a full frame', blurb: 'With ORDER BY, the default frame ends at the current row — so LAST_VALUE looks like FIRST_VALUE until you widen it to UNBOUNDED FOLLOWING.', code: 'LAST_VALUE(price) OVER (\n  ORDER BY day\n  ROWS BETWEEN UNBOUNDED PRECEDING\n           AND UNBOUNDED FOLLOWING)', lang: 'sql' },
  { id: 'b_sqt_ranks', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'ROW_NUMBER vs RANK vs DENSE_RANK', blurb: 'ROW_NUMBER: always 1,2,3 (no ties). RANK: ties share a number, then it skips (1,1,3). DENSE_RANK: ties share, no gap (1,1,2).', code: 'RANK() OVER (ORDER BY score DESC)', lang: 'sql' },
  { id: 'b_sqt_topn', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'Top-N per group with a ranked CTE', blurb: "Number rows within each partition, then filter in an outer query — the standard 'top 3 per category' pattern.", code: 'WITH r AS (\n  SELECT *, ROW_NUMBER() OVER (\n    PARTITION BY dept ORDER BY salary DESC) rn\n  FROM emp)\nSELECT * FROM r WHERE rn <= 3;', lang: 'sql' },
  { id: 'b_sqt_leadlag', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'LAG looks back, LEAD looks ahead', blurb: 'They pull a value from a previous or next row in the ordered window — the basis of period-over-period change.', code: 'LAG(revenue) OVER (ORDER BY month) AS prev_month', lang: 'sql' },
  { id: 'b_sqt_leadlag_use', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'Month-over-month with LAG', blurb: 'Subtract the lagged value from the current row to get the delta or growth rate — no self-join required.', code: 'revenue - LAG(revenue) OVER (ORDER BY month)\n  AS mom_change', lang: 'sql' },
  { id: 'b_sqt_selfjoin', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'A self-join joins a table to itself', blurb: 'Alias the table twice to relate rows within it — employees to their managers, or pairs in a group. Add a.id < b.id to drop mirror duplicates.', code: 'FROM employees e\nJOIN employees m ON e.manager_id = m.id;', lang: 'sql' },
  { id: 'b_sqt_union', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'UNION dedupes, UNION ALL keeps all', blurb: 'Both stack two result sets vertically. UNION removes duplicate rows (and pays to sort); UNION ALL keeps every row and is faster.', code: 'SELECT id FROM a\nUNION ALL\nSELECT id FROM b;', lang: 'sql' },
  { id: 'b_sqt_intersect', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'INTERSECT: rows in both', blurb: "It returns only rows appearing in both queries — the overlap. Think 'users who bought A and B'.", code: 'SELECT user_id FROM bought_a\nINTERSECT\nSELECT user_id FROM bought_b;', lang: 'sql' },
  { id: 'b_sqt_except', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'EXCEPT: in the first, not the second', blurb: "Rows from the first query that aren't in the second — the difference. 'Signed up but never purchased.'", code: 'SELECT user_id FROM signups\nEXCEPT\nSELECT user_id FROM purchases;', lang: 'sql' },
  { id: 'b_sqt_setop_rules', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'Set operations need matching columns', blurb: 'UNION, INTERSECT and EXCEPT require both queries to have the same number of columns, in the same order, with compatible types.' },
  { id: 'b_sqt_orderexec', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'SQL runs FROM before SELECT', blurb: "Logical order: FROM/JOIN, WHERE, GROUP BY, HAVING, SELECT, ORDER BY, LIMIT. That's why a SELECT alias can't be used in WHERE but can in ORDER BY." },
  { id: 'b_sqt_bestpractice', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'Clean SQL reads like a paragraph', blurb: 'Uppercase keywords, snake_case names, meaningful aliases, one clause per line, explicit JOIN types, no SELECT * in production. Future-you is the reader.' },
  { id: 'b_sqt_pivot', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'Pivot rows into columns with CASE', blurb: 'Wrap a CASE inside an aggregate, one per target column, and GROUP BY the row key — turns long data wide.', code: "SELECT user_id,\n  SUM(CASE WHEN platform='ios' THEN mins END) AS ios,\n  SUM(CASE WHEN platform='web' THEN mins END) AS web\nFROM usage GROUP BY user_id;", lang: 'sql' },
  { id: 'b_sqt_unpivot', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'Unpivot columns into rows with UNION ALL', blurb: 'Stack one SELECT per column, each labelling its source — turns wide data long, the shape most aggregates want.', code: "SELECT user_id, 'ios' AS platform, ios AS mins FROM t\nUNION ALL\nSELECT user_id, 'web', web FROM t;", lang: 'sql' },
  { id: 'b_sqt_str_case', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'UPPER / LOWER normalise text', blurb: "Fold case before comparing or grouping so 'Gmail' and 'gmail' match. Often paired with TRIM to tidy messy input.", code: 'WHERE LOWER(email) = LOWER(:input);', lang: 'sql' },
  { id: 'b_sqt_str_sub', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'Slice strings: LEFT, RIGHT, SUBSTRING', blurb: 'LEFT(s, n) / RIGHT(s, n) take from the ends; SUBSTRING(s FROM p FOR n) takes a middle slice; LENGTH(s) measures.', code: 'SELECT LEFT(phone, 3) AS area_code\nFROM contacts;', lang: 'sql' },
  { id: 'b_sqt_str_trim', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'TRIM strips surrounding spaces', blurb: 'TRIM removes leading and trailing spaces (LTRIM/RTRIM do one side, BTRIM both). Essential for data typed by humans.', code: 'SELECT TRIM(name) FROM imports;', lang: 'sql' },
  { id: 'b_sqt_str_concat', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'CONCAT joins, CONCAT_WS adds a separator', blurb: 'CONCAT(a, b) glues values; CONCAT_WS(sep, a, b, c) inserts the separator between them and skips NULLs.', code: "SELECT CONCAT_WS(' ', first, last) AS full_name\nFROM users;", lang: 'sql' },
  { id: 'b_sqt_str_split', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'SPLIT_PART and POSITION dissect text', blurb: 'SPLIT_PART(s, delim, n) grabs the n-th chunk; POSITION(sub IN s) finds where a substring starts (0 if absent).', code: "SELECT SPLIT_PART(email, '@', 2) AS domain\nFROM users;", lang: 'sql' },
  { id: 'b_sqt_casestudy', pack: 'sql-tutorial', topic: 'sql', level: 3, title: 'Analytics is question -> query -> story', blurb: 'A real case study starts from a business question, breaks it into aggregates and window functions, then reads the numbers back as a recommendation. SQL is the middle step, not the point.' },
];

/** Everything a "load starter pack" ships — every bundled pack. */
export const ALL_SEED_BYTES: Omit<ByteCard, 'updatedAt'>[] = [
  ...STARTER_BYTES,
  ...SQL_BYTES,
  ...SQL_TUTORIAL_BYTES,
  ...PYTHON_BYTES,
  ...ALGO_BYTES,
  ...ML_BYTES,
  ...AI_BYTES,
  ...CS_BYTES,
];
